algoritmo "semnome"
// Função :Desenvolva um algoritmo que lê e escreve os números ímpares de 1 a 500
// Autor :
// Data : 13/03/2014
// Seção de Declarações 
var
num, x,impares:inteiro
inicio
// Seção de Comandos
para x de 1 ate 500 faca
escreva ("digite um numeros:")
leia (num)
se num >= 1 entao
se num <= 500 entao
impares <-impares + 1
fimse
fimse
fimpara
escreval(" ao total, foram digitados", impares,"numero impares entre 1 e 500")

fimalgoritmo
